---
AWSTemplateFormatVersion: 2010-09-09
Description: CodePipeline Py Lambda Versioner SNS Stack

Parameters:
  Email:
    Type: String

Resources:
  CodePipelineSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !Ref Email
          Protocol: email

Outputs:
  CodePipelineSNSTopic:
    Value: !Ref CodePipelineSNSTopic
